export const HEADER_MAX_HEIGHT = 420
export const HEADER_MIN_HEIGHT = 180
export const SCROLL_DISTANCE = HEADER_MAX_HEIGHT - HEADER_MIN_HEIGHT

export const ICONS_BUTTONS_MAX_TOP = 0
export const ICONS_BUTTONS_MIN_TOP = -230
